// High-fidelity mock product catalog matching Luxury-Website-html catalog
// Used during development before Shopify API is connected

export interface Product {
  id: string;
  handle: string;
  name: string;
  category: string;
  gender: string;
  price: number;
  formattedPrice: string;
  rating: number;
  image: string;
  hoverImage?: string;
  badge?: string;
  badgeStyle?: 'olive' | 'default';
  swatches: { color: string; hex: string; img?: string | null; variantId?: string | null }[];
  sizes: string[];
  materials: string[];
  stock: 'in' | 'pre';
  filterCategory: string;
  filterColors: string[];
  filterSizes: string[];
  filterMaterials: string[];
  description: string;
  isFeatured?: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
}

export const products: Product[] = [
  {
    id: 'p1',
    handle: 'sand-linen-blazer',
    name: 'Sand Linen Blazer',
    category: 'Men · Tailoring',
    gender: 'men',
    price: 520,
    formattedPrice: '€520',
    rating: 4.6,
    image: 'Product Image 1.png',
    badge: 'New',
    badgeStyle: 'olive',
    swatches: [
      { color: 'sand', hex: '#C2AE8E' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['linen'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['sand', 'stone'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['linen'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isNew: true,
  },
  {
    id: 'p2',
    handle: 'camel-wool-overcoat',
    name: 'Camel Wool Overcoat',
    category: 'Women · Outerwear',
    gender: 'women',
    price: 690,
    formattedPrice: '€690',
    rating: 4.7,
    image: 'Product Image 2.png',
    swatches: [
      { color: 'olive', hex: '#6B705E' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['s', 'm', 'l'],
    materials: ['wool'],
    stock: 'in',
    filterCategory: 'outerwear',
    filterColors: ['olive', 'stone'],
    filterSizes: ['s', 'm', 'l'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isBestSeller: true,
  },
  {
    id: 'p3',
    handle: 'pleated-wide-trouser',
    name: 'Pleated Wide Trouser',
    category: 'Women · Tailoring',
    gender: 'women',
    price: 280,
    formattedPrice: '€280',
    rating: 4.8,
    image: 'Product Image 3.png',
    badge: 'Atelier',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['wool'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['charcoal', 'stone'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isFeatured: true,
  },
  {
    id: 'p4',
    handle: 'ribbed-wool-knit',
    name: 'Ribbed Wool Knit',
    category: 'Men · Knitwear',
    gender: 'men',
    price: 240,
    formattedPrice: '€240',
    rating: 4.9,
    image: 'Product Image 4.png',
    swatches: [
      { color: 'sage', hex: '#B8BCA9' },
      { color: 'ecru', hex: '#E4E6DA' },
      { color: 'olive', hex: '#6B705E' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['wool'],
    stock: 'in',
    filterCategory: 'knitwear',
    filterColors: ['sage', 'ecru', 'olive'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isBestSeller: true,
  },
  {
    id: 'p5',
    handle: 'relaxed-denim-jacket',
    name: 'Relaxed Denim Jacket',
    category: 'Unisex · Denim',
    gender: 'unisex',
    price: 320,
    formattedPrice: '€320',
    rating: 5.0,
    image: 'Product Image 5.png',
    badge: 'New',
    badgeStyle: 'olive',
    swatches: [
      { color: 'stone', hex: '#858A76' },
      { color: 'charcoal', hex: '#30382C' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['denim'],
    stock: 'in',
    filterCategory: 'denim',
    filterColors: ['stone', 'charcoal'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['denim'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p6',
    handle: 'belted-cotton-trench',
    name: 'Belted Cotton Trench',
    category: 'Women · Outerwear',
    gender: 'women',
    price: 560,
    formattedPrice: '€560',
    rating: 4.6,
    image: 'Product Image 6.png',
    swatches: [
      { color: 'stone', hex: '#858A76' },
      { color: 'olive', hex: '#6B705E' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['cotton'],
    stock: 'in',
    filterCategory: 'outerwear',
    filterColors: ['stone', 'olive'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['cotton'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isFeatured: true,
  },
  {
    id: 'p7',
    handle: 'two-piece-tailored-suit',
    name: 'Two-Piece Tailored Suit',
    category: 'Men · Tailoring',
    gender: 'men',
    price: 740,
    formattedPrice: '€740',
    rating: 4.7,
    image: 'Product Image 7.png',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'olive', hex: '#6B705E' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['wool'],
    stock: 'pre',
    filterCategory: 'tailoring',
    filterColors: ['charcoal', 'olive'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
  },
  {
    id: 'p8',
    handle: 'cropped-wool-cardigan',
    name: 'Cropped Wool Cardigan',
    category: 'Women · Knitwear',
    gender: 'women',
    price: 260,
    formattedPrice: '€260',
    rating: 4.8,
    image: 'Product Image 8.png',
    swatches: [
      { color: 'ecru', hex: '#E4E6DA' },
      { color: 'sage', hex: '#B8BCA9' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['wool', 'cashmere'],
    stock: 'in',
    filterCategory: 'knitwear',
    filterColors: ['ecru', 'sage'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['wool', 'cashmere'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isBestSeller: true,
  },
  {
    id: 'p9',
    handle: 'wide-leg-linen-trouser',
    name: 'Wide-Leg Linen Trouser',
    category: 'Women · Tailoring',
    gender: 'women',
    price: 220,
    formattedPrice: '€220',
    rating: 4.7,
    image: 'Product Image 9.png',
    swatches: [
      { color: 'ecru', hex: '#E4E6DA' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['xs', 's', 'm', 'l', 'xl'],
    materials: ['linen'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['ecru', 'stone'],
    filterSizes: ['xs', 's', 'm', 'l', 'xl'],
    filterMaterials: ['linen'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isFeatured: true,
  },
  {
    id: 'p10',
    handle: 'oversized-linen-shirt',
    name: 'Oversized Linen Shirt',
    category: 'Unisex · Essentials',
    gender: 'unisex',
    price: 195,
    formattedPrice: '€195',
    rating: 4.9,
    image: 'Product Image 10.png',
    badge: 'New',
    badgeStyle: 'olive',
    swatches: [
      { color: 'sage', hex: '#B8BCA9' },
      { color: 'ecru', hex: '#E4E6DA' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['linen'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['sage', 'ecru', 'stone'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['linen'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p11',
    handle: 'structured-linen-blazer',
    name: 'Structured Linen Blazer',
    category: 'Women · Tailoring',
    gender: 'women',
    price: 520,
    formattedPrice: '€520',
    rating: 4.8,
    image: 'Product Image 11.png',
    swatches: [
      { color: 'olive', hex: '#6B705E' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['linen'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['olive', 'stone'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['linen'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
  },
  {
    id: 'p12',
    handle: 'cashmere-turtleneck',
    name: 'Cashmere Turtleneck',
    category: 'Men · Knitwear',
    gender: 'men',
    price: 380,
    formattedPrice: '€380',
    rating: 4.9,
    image: 'Product Image 12.png',
    badge: 'Atelier',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'stone', hex: '#858A76' },
      { color: 'ecru', hex: '#E4E6DA' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['cashmere'],
    stock: 'in',
    filterCategory: 'knitwear',
    filterColors: ['charcoal', 'stone', 'ecru'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['cashmere'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isFeatured: true,
  },
  {
    id: 'p13',
    handle: 'wool-pencil-skirt',
    name: 'Wool Pencil Skirt',
    category: 'Women · Tailoring',
    gender: 'women',
    price: 240,
    formattedPrice: '€240',
    rating: 4.6,
    image: 'Product Image 13.png',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'sage', hex: '#B8BCA9' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['wool'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['charcoal', 'sage'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
  },
  {
    id: 'p14',
    handle: 'selvedge-denim-trouser',
    name: 'Selvedge Denim Trouser',
    category: 'Men · Denim',
    gender: 'men',
    price: 295,
    formattedPrice: '€295',
    rating: 4.7,
    image: 'Product Image 14.png',
    badge: 'New',
    badgeStyle: 'olive',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['denim'],
    stock: 'in',
    filterCategory: 'denim',
    filterColors: ['charcoal', 'stone'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['denim'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isNew: true,
  },
  {
    id: 'p15',
    handle: 'silk-slip-dress',
    name: 'Silk Slip Dress',
    category: 'Women · Dresses',
    gender: 'women',
    price: 360,
    formattedPrice: '€360',
    rating: 4.8,
    image: 'Product Image 15.png',
    swatches: [
      { color: 'sage', hex: '#B8BCA9' },
      { color: 'ecru', hex: '#E4E6DA' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['wool'],
    stock: 'in',
    filterCategory: 'outerwear',
    filterColors: ['sage', 'ecru'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isBestSeller: true,
  },
  {
    id: 'p16',
    handle: 'atelier-overshirt',
    name: 'The Atelier Overshirt',
    category: 'Unisex · Essentials',
    gender: 'unisex',
    price: 340,
    formattedPrice: '€340',
    rating: 4.9,
    image: 'Product Image 16.png',
    badge: 'Atelier',
    swatches: [
      { color: 'olive', hex: '#6B705E' },
      { color: 'stone', hex: '#858A76' },
      { color: 'charcoal', hex: '#30382C' },
    ],
    sizes: ['s', 'm', 'l', 'xl'],
    materials: ['cotton'],
    stock: 'in',
    filterCategory: 'tailoring',
    filterColors: ['olive', 'stone', 'charcoal'],
    filterSizes: ['s', 'm', 'l', 'xl'],
    filterMaterials: ['cotton'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: 'p17',
    handle: 'merino-roll-neck',
    name: 'Merino Roll Neck',
    category: 'Women · Knitwear',
    gender: 'women',
    price: 210,
    formattedPrice: '€210',
    rating: 4.7,
    image: 'Product Image 17.png',
    swatches: [
      { color: 'ecru', hex: '#E4E6DA' },
      { color: 'charcoal', hex: '#30382C' },
      { color: 'olive', hex: '#6B705E' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['wool'],
    stock: 'in',
    filterCategory: 'knitwear',
    filterColors: ['ecru', 'charcoal', 'olive'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['wool'],
    description: 'A considered piece in natural fibres, finished by hand in our Paris atelier and made to be kept for years.',
  },
  {
    id: 'p18',
    handle: 'leather-tote-bag',
    name: 'Leather Tote Bag',
    category: 'Bags',
    gender: 'unisex',
    price: 780,
    formattedPrice: '€780',
    rating: 4.9,
    image: 'Product Image 18.png',
    badge: 'New',
    badgeStyle: 'olive',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'stone', hex: '#858A76' },
    ],
    sizes: ['one-size'],
    materials: ['leather'],
    stock: 'in',
    filterCategory: 'accessories',
    filterColors: ['charcoal', 'stone'],
    filterSizes: ['one-size'],
    filterMaterials: ['leather'],
    description: 'A considered piece crafted in full-grain vegetable-tanned leather, finished by hand in our Paris atelier.',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p19',
    handle: 'lambskin-shoulder-bag',
    name: 'Lambskin Shoulder Bag',
    category: 'Bags',
    gender: 'unisex',
    price: 640,
    formattedPrice: '€640',
    rating: 4.8,
    image: 'Product Image 19.png',
    swatches: [
      { color: 'ecru', hex: '#E4E6DA' },
      { color: 'charcoal', hex: '#30382C' },
    ],
    sizes: ['one-size'],
    materials: ['leather'],
    stock: 'in',
    filterCategory: 'accessories',
    filterColors: ['ecru', 'charcoal'],
    filterSizes: ['one-size'],
    filterMaterials: ['leather'],
    description: 'A considered piece crafted in lambskin nappa leather, finished by hand in our Paris atelier.',
  },
  {
    id: 'p20',
    handle: 'wool-cashmere-coat',
    name: 'Wool-Cashmere Coat',
    category: 'Women · Outerwear',
    gender: 'women',
    price: 890,
    formattedPrice: '€890',
    rating: 4.9,
    image: 'Product Image 20.png',
    badge: 'Atelier',
    swatches: [
      { color: 'charcoal', hex: '#30382C' },
      { color: 'olive', hex: '#6B705E' },
      { color: 'ecru', hex: '#E4E6DA' },
    ],
    sizes: ['xs', 's', 'm', 'l'],
    materials: ['wool', 'cashmere'],
    stock: 'pre',
    filterCategory: 'outerwear',
    filterColors: ['charcoal', 'olive', 'ecru'],
    filterSizes: ['xs', 's', 'm', 'l'],
    filterMaterials: ['wool', 'cashmere'],
    description: 'An exceptional piece in our 60% wool 40% cashmere blend, finished by hand in our Paris atelier.',
    isFeatured: true,
    isBestSeller: true,
  },
];

export const featuredProducts = products.filter(p => p.isFeatured).slice(0, 4);
export const newArrivals = products.filter(p => p.isNew).slice(0, 4);
export const bestSellers = products.filter(p => p.isBestSeller).slice(0, 4);

export function getProductByHandle(handle: string): Product | undefined {
  return products.find(p => p.handle === handle);
}
